apiVersion: v1
kind: Service
metadata:
  name: joblisting-backend-service
  namespace: joblisting
spec:
  selector:
    app: joblisting-backend
  ports:
    - port: 8080        # Service port inside cluster
      targetPort: 8080  # Container port
  type: ClusterIP
