apiVersion: apps/v1
kind: Deployment
metadata:
  name: joblisting-backend-deployment
  namespace: joblisting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joblisting-backend
  template:
    metadata:
      labels:
        app: joblisting-backend
    spec:
      containers:
        - name: joblisting-backend
          image: jmmanu/jobportal-backend:latest    # <-- FIXED IMAGE NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://manu:root123@cluster0.r7jbx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "joblisting"
